import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: "#BD202E"
  },
  scrollContent: { 
    flexGrow: 1,
    paddingBottom: 20 
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#BD202E",
    borderBottomWidth: 1,
    borderBottomColor: "#a01b26",
  },
  appTitle: { 
    fontSize: 20, 
    fontWeight: "700", 
    color: "#ffffff",
    letterSpacing: 0.3,
    fontFamily: "Poppins",
  },
  headerIcons: { flexDirection: "row", gap: 8 },
  iconBtn: { padding: 4 },
  menuIconStyle: {
    marginRight: 12,
  },
  permissionIconStyle: {
    marginRight: 12,
  },
  drawerOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-start",
  },
  drawerContainer: {
    width: "70%",
    height: "100%",
    backgroundColor: "#BD202E",
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
    borderRightWidth: 1,
    borderRightColor: "#CBD5E1",
  },
  drawerHeader: {
    alignItems: "center",
    paddingVertical: 30,
    paddingHorizontal: 20,
    backgroundColor: "#BD202E",
    borderBottomWidth: 1,
    borderBottomColor: "#CBD5E1",
  },
  drawerLogo: {
    width: 80,
    height: 80,
    marginBottom: 10,
  },
  drawerBrand: {
    fontSize: 16,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 5,
    letterSpacing: 0.2,
  },
  drawerVersion: {
    fontSize: 13,
    color: "#ffffff",
    marginBottom: 15,
  },
  drawerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#ffffff",
    letterSpacing: 0.2,
    fontFamily: "Poppins",
  },
  menuList: {
    paddingVertical: 10,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  menuText: {
    flex: 1,
    fontSize: 16,
    fontWeight: "600",
    color: "#ffffff",
    fontFamily: "Poppins",
  },
  menuArrow: {
    fontSize: 24,
    color: "#ffffff",
  },
  permissionsContainer: {
    flex: 1,
    backgroundColor: "#BD202E",
  },
  permissionsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#BD202E",
    borderBottomWidth: 1,
    borderBottomColor: "#CBD5E1",
  },
  permissionsTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#ffffff",
    fontFamily: "Poppins",
  },
  permissionsClose: {
    fontSize: 28,
    color: "#ffffff",
    fontWeight: "700",
  },
  permissionsList: {
    flex: 1,
    paddingHorizontal: 16,
  },
  permissionsSubtitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#ffffff",
    marginTop: 20,
    marginBottom: 16,
  },
  permissionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#BD202E",
    padding: 16,
    marginBottom: 12,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  permissionInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  permissionTextContainer: {
    flex: 1,
  },
  permissionName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 4,
  },
  permissionDesc: {
    fontSize: 12,
    color: "#ffffff",
    lineHeight: 16,
  },
  permissionToggle: {
    marginLeft: 12,
  },
  openSettingsBtn: {
    backgroundColor: "#BD202E",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 20,
    marginBottom: 16,
  },
  openSettingsBtnText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
    textAlign: "center",
  },
  permissionsNote: {
    fontSize: 12,
    color: "#ffffff",
    textAlign: "center",
    marginTop: 12,
    marginBottom: 12,
    paddingHorizontal: 20,
    lineHeight: 18,
    fontWeight: "600",
  },
  permissionsInfo: {
    fontSize: 12,
    color: "#ffffff",
    textAlign: "center",
    marginBottom: 20,
    paddingHorizontal: 20,
    lineHeight: 18,
  },
  userGuideContainer: {
    flex: 1,
    backgroundColor: "#BD202E",
  },
  userGuideHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#BD202E",
    borderBottomWidth: 1,
    borderBottomColor: "#CBD5E1",
  },
  userGuideTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#ffffff",
    fontFamily: "Poppins",
  },
  userGuideClose: {
    fontSize: 28,
    color: "#ffffff",
    fontWeight: "700",
  },
  userGuideContent: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  guideSection: {
    backgroundColor: "#BD202E",
    padding: 16,
    marginBottom: 12,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  guideSectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 12,
  },
  guideSubtitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#ffffff",
    marginBottom: 8,
  },
  guideText: {
    fontSize: 14,
    color: "#ffffff",
    lineHeight: 20,
  },
  guideList: {
    marginTop: 8,
  },
  guideListItem: {
    fontSize: 14,
    color: "#ffffff",
    marginBottom: 8,
    lineHeight: 20,
  },
  guideListText: {
    color: "#ffffff",
    lineHeight: 20,
  },
  guideSteps: {
    marginTop: 8,
  },
  guideStep: {
    fontSize: 14,
    color: "#ffffff",
    marginBottom: 10,
    lineHeight: 20,
  },
  debugContainer: { flex: 1, backgroundColor: "#BD202E" },
  debugHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  debugTitle: { fontSize: 18, fontWeight: "700", color: "#ffffff" },
  debugClose: { fontSize: 24, color: "#ffffff", fontWeight: "700" },
  clearLogsBtn: {
    marginHorizontal: 16,
    marginTop: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: "#BD202E",
    borderRadius: 6,
  },
  clearLogsBtnText: { color: "#ffffff", fontWeight: "600", textAlign: "center" },
  logScroll: { flex: 1, paddingHorizontal: 8 },
  noLogs: { color: "#ffffff", fontSize: 14, textAlign: "center", marginTop: 20 },
  logEntry: {
    flexDirection: "row",
    padding: 8,
    marginVertical: 4,
    marginHorizontal: 4,
    borderRadius: 6,
    backgroundColor: "#BD202E",
    borderLeftWidth: 3,
    borderLeftColor: "#666",
  },
  logError: { borderLeftColor: "#d32f2f", backgroundColor: "#BD202E" },
  logWarn: { borderLeftColor: "#ff9800", backgroundColor: "#BD202E" },
  logInfo: { borderLeftColor: "#2596be", backgroundColor: "#BD202E" },
  logTime: { fontSize: 11, color: "#ffffff", marginRight: 8, minWidth: 60 },
  logType: { fontSize: 11, fontWeight: "700", color: "#ffffff", marginRight: 8, minWidth: 60 },
  logMessage: { fontSize: 12, color: "#ffffff", flex: 1, flexWrap: "wrap" },
  sectionTitleContainer: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 12,
    padding: 12,
    backgroundColor: "#BD202E",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    shadowColor: "#BD202E",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#ffffff",
    textAlign: "center",
    letterSpacing: 0.3,
    fontFamily: "Poppins",
  },
  compassGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 16,
    gap: 12,
    justifyContent: "space-between",
  },
  compassCard: {
    width: "48%",
    backgroundColor: "#BD202E",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    shadowColor: "#BD202E",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#CBD5E1",
  },
  compassImageContainer: {
    width: 120,
    height: 120,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 60,
    overflow: "hidden",
    backgroundColor: "#BD202E",
    borderWidth: 1,
      borderColor: "#CBD5E1",
  },
  compassDial: {
    width: 120,
    height: 120,
    alignSelf: "center",
  },
  compassNeedle: {
    width: 80,
    height: 80,
    position: "absolute",
    alignSelf: "center",
  },
  compassLabel: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: "700",
      color: "#ffffff",
    textAlign: "center",
    letterSpacing: 0.2,    fontFamily: "Poppins",  },
  bottomButtons: {
    flexDirection: "row",
    paddingHorizontal: 16,
    gap: 12,
    marginTop: 8,
  },
  bottomBtn: {
    flex: 1,
    backgroundColor: "#BD202E",
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
      borderColor: "#CBD5E1",
      shadowColor: "#BD202E",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
    minHeight: 52,
    justifyContent: "center",
    alignItems: "center",
  },
  bottomBtnText: {
    fontSize: 14,
    fontWeight: "700",
      color: "#ffffff",
    textAlign: "center",
    letterSpacing: 0.2,    fontFamily: "Poppins",  },
  logoContainer: {
    alignItems: "center",
    marginTop: 20,
    marginBottom: 10,
  },
  logo: {
    width: 150,
    height: 60,
  },
  cameraContainer: { flex: 1, backgroundColor: "#BD202E" },
  camera: { flex: 1 },
  fullScreenOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "space-between",
    alignItems: "center",
  },
  compassOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 1000,
    overflow: "hidden",
  },
  directionBreakdown: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    width: "100%",
    paddingVertical: 16,
    paddingHorizontal: 12,
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    gap: 8,
  },
  directionItem: {
    alignItems: "center",
    flex: 1,
  },
  dirLabel: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 4,
  },
  dirValue: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  overlayNeedle: { position: "absolute" },
  headingBadge: {
    position: "absolute",
    bottom: "30%",
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 14,
  },
  headingBadgeText: { color: "#ffffff", fontSize: 18, fontWeight: "700" },
  cameraControls: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: "#BD202E",
  },
  camBtn: {
    paddingVertical: 10,
    paddingHorizontal: 16,
      backgroundColor: "#BD202E",
    borderRadius: 8,
  },
  camBtnText: { color: "#ffffff", fontWeight: "600" },
  capture: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#BD202E",
    borderWidth: 4,
      borderColor: "#CBD5E1",
  },
  cameraPermission: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  permissionText: { color: "#ffffff", fontSize: 16 },
  previewContainer: { flex: 1 },
  previewShot: { flex: 1, width: "100%", height: "100%" },
  previewShotInner: { flex: 1, width: "100%", height: "100%" },
  preview: { flex: 1, width: "100%" },
  previewControls: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: "#BD202E",
    gap: 8,
  },
});
